package com.bank.bian.partylifecyclemanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Party Lifecycle Management
 *
 * Business Area:      Sales and Service
 * Business Domain:    Customer Management
 * Functional Pattern: Manage
 * Asset Type:         Party Record
 * Control Record:     Party Record Management Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Party Lifecycle Management — BIAN Semantic API")
                .description("Service Domain 'Party Lifecycle Management' (Manage pattern) "
                        + "operating on the 'Party Record Management Plan' control record.")
                .version("0.1.0"));
    }
}
