apiVersion: v2
name: sd-party-lifecycle-management
description: "BIAN Service Domain: Party Lifecycle Management (Manage pattern, Sales and Service)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - manage
annotations:
  bian/business-area: "Sales and Service"
  bian/business-domain: "Customer Management"
  bian/asset-type: "Party Record"
  bian/control-record: "Party Record Management Plan"
